import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <nav className="flex flex-row ">
                    <Link className={'text-blue-600 underline hover:text-blue-800 m-2'} href="/">Home</Link>
                    <Link className={'text-blue-600 underline hover:text-blue-800 m-2'} href="/testing">Testing Sloppa</Link>
                    <Link className={'text-blue-600 underline hover:text-blue-800 m-2'} href="/serversidequery">Serverside query
                        testing</Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
